include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-raw-types: true
  errors:
    todo: ignore

linter:
  rules:
    - prefer_const_constructors
    - prefer_final_locals
    - avoid_print          # 一律用 LoggingService，不用 print
    - unawaited_futures
